/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author acer
 */
public class popup_inputhasilforum extends javax.swing.JFrame {

    /**
     * Creates new form popup_inputpinjaman
     */
    public popup_inputhasilforum() {
       
        initComponents();
         setLocationRelativeTo(this);
    }

    public String[] getdata() {
        String[] data = new String[6];
        data[0] = judul.getText();
        data[1] = isi.getText();
        data[2] = IdPengguna.getText();
        data[3] = selesai.getSelectedItem().toString();
        data[4]=id_masalah.getText();
        data[5]=hasil.getText();
        System.out.println("selesai = " + data[3]);
        return data;
    }

    public void setdatainput(String[] data) {
        id_masalah.setText("ndak tau");
        IdPengguna.setText(data[0]);
        nama.setText(data[3]);
        tanggalinput.setText(data[1]);
    }

    public void setdataubah(String[] data, String username) {
         System.out.println("id masalah"+data[0]);
        id_masalah.setText(data[0]);
       
        IdPengguna.setText(data[1]);
        System.out.println("idpengguna"+data[1]);
        judul.setText(data[2]);
        System.out.println("judul "+data[2]);
        isi.setText(data[3]);
        System.out.println("isi "+data[3]);
//        selesai.setSelectedIndex(Integer.parseInt(data[5]));
        nama.setText(username);
        hasil.setText(data[5]);
        System.out.println("hasil "+data[5]);
        
    }
public void setenablehasil (boolean set){
hasil.setEnabled(set);
}
    public void setsimpan(String set) {
        btnSimpan.setText(set);
    }

    public String getbtnsimpan() {
        return btnSimpan.getText();
    }

    public void simpan(ActionListener a) {
        btnSimpan.addActionListener(a);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_masalah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        keterangan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tanggalinput = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        IdPengguna = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTextArea();
        selesai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Isikan ketentuan Berikut Ini");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, -1, -1));

        id_masalah.setEditable(false);
        getContentPane().add(id_masalah, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 60, 251, -1));

        jLabel2.setText("id masalah");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, -1));

        jLabel4.setText("judul");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 251, -1));

        keterangan.setText("isi");
        getContentPane().add(keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setText("Tanggal input");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel7.setText("nama");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 93, -1, -1));

        nama.setEditable(false);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 91, 143, -1));

        tanggalinput.setEditable(false);
        getContentPane().add(tanggalinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 200, -1));

        btnSimpan.setText("simpan");
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 313, -1, -1));

        IdPengguna.setEditable(false);
        getContentPane().add(IdPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 91, 251, -1));

        jLabel8.setText("id_Pengguna");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 93, -1, -1));

        isi.setColumns(20);
        isi.setRows(5);
        jScrollPane1.setViewportView(isi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 110));

        selesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel3.setText("selesai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel5.setText("hasil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        hasil.setEditable(false);
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 360, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_inputhasilforum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_inputhasilforum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_inputhasilforum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_inputhasilforum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup_inputhasilforum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdPengguna;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField id_masalah;
    private javax.swing.JTextArea isi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judul;
    private javax.swing.JLabel keterangan;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> selesai;
    private javax.swing.JTextField tanggalinput;
    // End of variables declaration//GEN-END:variables
}
